services:
  apache:
    image: httpd:2.4
    container_name: apache2-server
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - .:/usr/local/apache2/htdocs
      - ./ssl:/etc/apache2/ssl/